// app/llms.txt/route.js
// Root-level /llms.txt — AI-optimized sitemap for every site
// Auto-generated from the site's pages, no configuration needed

import { generateSitemapAndRss } from '../../core/render/sitemap';
import { getSite } from '../../core/sites/files';
import { resolveSite } from '../../core/sites/resolve';

function generateLlmsTxt(entries, siteMeta, baseUrl) {
  const siteName = siteMeta.title || 'Website';
  const siteDescription = siteMeta.description || 'No description available';

  let output = `# ${siteName}\n\n`;
  output += `## About\n${siteDescription}\n\n`;

  const pages = entries.filter(e => !e.title || e.priority >= 0.9);
  const posts = entries.filter(e => e.title && e.priority < 0.9);

  if (pages.length > 0) {
    output += `## Public Pages\n\n`;
    for (const entry of pages) {
      const url = entry.url.startsWith('http') ? entry.url : `${baseUrl}${entry.url}`;
      const title = entry.title || url.split('/').pop() || 'Home';
      const description = entry.description ? ` - ${entry.description}` : '';
      output += `- ${title}: ${url}${description}\n`;
    }
    output += '\n';
  }

  if (posts.length > 0) {
    output += `## Blog Posts\n\n`;
    for (const entry of posts) {
      const url = entry.url.startsWith('http') ? entry.url : `${baseUrl}${entry.url}`;
      const title = entry.title || 'Untitled';
      const description = entry.description ? ` - ${entry.description.substring(0, 150)}` : '';
      output += `- ${title}: ${url}${description}\n`;
    }
    output += '\n';
  }

  output += `## Structured Data\n\n`;
  output += `- Total Pages: ${pages.length}\n`;
  output += `- Total Blog Posts: ${posts.length}\n`;
  output += `- Last Updated: ${new Date().toISOString().split('T')[0]}\n`;
  output += `- Language: ${siteMeta.lang || 'en'}\n`;

  if (siteMeta.contact || siteMeta.email) {
    output += `\n## Contact\n`;
    if (siteMeta.email) output += `- Email: ${siteMeta.email}\n`;
    if (siteMeta.contact) output += `- ${siteMeta.contact}\n`;
  }

  output += `\n---\nGenerated by JasonJS Framework\n`;
  output += `For more information, visit: ${baseUrl}\n`;

  return output;
}

export async function GET() {
  const { host } = await resolveSite();
  const baseUrl = `https://${host}`;

  try {
    const site = await getSite(host);
    if (!site) {
      return new Response('Site not found', { status: 404 });
    }

    const { entries, siteMeta } = await generateSitemapAndRss(
      site._id || site.domain || host,
      baseUrl
    );

    const formattedEntries = entries.map(entry => ({
      ...entry,
      url: entry.url.startsWith('http') ? entry.url : `${baseUrl}${entry.url}`,
      lastModified: entry.lastModified instanceof Date
        ? entry.lastModified
        : new Date(entry.lastModified || Date.now())
    }));

    const llmsTxt = generateLlmsTxt(formattedEntries, siteMeta, baseUrl);

    return new Response(llmsTxt, {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Cache-Control': 'public, max-age=3600',
      },
    });
  } catch (error) {
    console.error('Error generating llms.txt:', error);
    return new Response(`Error generating llms.txt: ${error.message}`, { status: 500 });
  }
}

export const dynamic = 'force-dynamic';
export const revalidate = 3600;
