// app/api/llms.txt/route.js
// AI-optimized sitemap for Generative Engine Optimization (GEO)
// Used by ChatGPT, Claude, Perplexity, and other AI search engines
import { generateSitemapAndRss } from '../../../core/render/sitemap';
import { getSite } from '../../../core/sites/files';
import { resolveSite } from '../../../core/sites/resolve';

/**
 * Generates plain text sitemap optimized for AI crawlers
 * @param {Array} entries - Sitemap entries
 * @param {Object} siteMeta - Site metadata
 * @param {string} baseUrl - Base URL of the site
 * @returns {string} - Formatted llms.txt content
 */
function generateLlmsTxt(entries, siteMeta, baseUrl) {
  const siteName = siteMeta.title || 'Website';
  const siteDescription = siteMeta.description || 'No description available';

  let output = `# ${siteName}\n\n`;
  output += `## About\n${siteDescription}\n\n`;

  // Separate regular pages from blog posts
  const pages = entries.filter(e => !e.title || e.priority >= 0.9);
  const posts = entries.filter(e => e.title && e.priority < 0.9);

  // Public Pages section
  if (pages.length > 0) {
    output += `## Public Pages\n\n`;
    pages.forEach(entry => {
      const url = entry.url.startsWith('http') ? entry.url : `${baseUrl}${entry.url}`;
      const title = entry.title || url.split('/').pop() || 'Home';
      const desc = entry.description ? `: ${entry.description}` : '';
      output += `- [${title}](${url})${desc}\n`;
    });
    output += '\n';
  }

  // Blog Posts / Articles section
  if (posts.length > 0) {
    output += `## Articles\n\n`;
    posts.forEach(entry => {
      const url = entry.url.startsWith('http') ? entry.url : `${baseUrl}${entry.url}`;
      const title = entry.title || 'Untitled';
      const desc = entry.description ? `\n  > ${entry.description.substring(0, 200)}` : '';
      output += `- [${title}](${url})${desc}\n`;
    });
    output += '\n';
  }

  // Structured Data section (key facts)
  output += `## Structured Data\n\n`;
  output += `- Total Pages: ${pages.length}\n`;
  output += `- Total Blog Posts: ${posts.length}\n`;
  output += `- Last Updated: ${new Date().toISOString().split('T')[0]}\n`;
  output += `- Language: ${siteMeta.lang || 'en'}\n`;

  // Contact section (if available)
  if (siteMeta.contact || siteMeta.email) {
    output += `\n## Contact\n`;
    if (siteMeta.email) {
      output += `- Email: ${siteMeta.email}\n`;
    }
    if (siteMeta.contact) {
      output += `- ${siteMeta.contact}\n`;
    }
  }

  output += `\n---\nGenerated by JasonJS Framework\n`;
  output += `For more information, visit: ${baseUrl}\n`;

  return output;
}

export async function GET() {
  const { host } = await resolveSite();
  const baseUrl = `https://${host}`;

  try {
    console.log(`Generating llms.txt for host: ${host}`);

    const site = await getSite(host);
    if (!site) {
      console.error(`Site not found for host: ${host}`);
      return new Response('Site not found', { status: 404 });
    }

    console.log(`Found site: ${site._id || site.domain || host}`);

    // Generate sitemap data (same as sitemap.xml but different format)
    const { entries, siteMeta } = await generateSitemapAndRss(
      site._id || site.domain || host,
      baseUrl
    );

    console.log(`Generated ${entries.length} entries for llms.txt`);

    // Format entries with full URLs
    const formattedEntries = entries.map(entry => ({
      ...entry,
      url: entry.url.startsWith('http') ? entry.url : `${baseUrl}${entry.url}`,
      lastModified: entry.lastModified instanceof Date
        ? entry.lastModified
        : new Date(entry.lastModified || Date.now())
    }));

    // Generate AI-optimized text format
    const llmsTxt = generateLlmsTxt(formattedEntries, siteMeta, baseUrl);

    console.log(`Successfully generated llms.txt`);

    // Return plain text with proper content type
    return new Response(llmsTxt, {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Cache-Control': 'public, max-age=3600' // 1 hour cache
      }
    });
  } catch (error) {
    console.error('Error generating llms.txt:', error);
    return new Response(`Error generating llms.txt: ${error.message}`, { status: 500 });
  }
}

// Set dynamic because we use headers() to get host
export const dynamic = 'force-dynamic';

export const revalidate = 3600; // Revalidate every hour
