// addons/notion-blog/components/Article.jsx
//
// Page metadata (title, description, OG, Twitter) is generated by the
// framework via core/render/metadata.js. It walks the page JSON, finds this
// component's `attributes.fields` mapping and `attributes.display.defaultImage`,
// and produces the full <head> metadata. This file only renders the article.
import React from 'react';
import Link from 'next/link';
import ServerImage from '../utils/ServerImage';
import ServerAudio from '../utils/ServerAudio';
import { renderBlock } from '../utils/Renderer';
import ShareButton from './ShareButton';

// Process blocks to properly handle nested lists.
//
// Tables: do nothing special. Notion's API returns `table_row` blocks as
// CHILDREN of the parent `table` block (not siblings), and the fetcher in
// core/databases/notion/index.js already populates `block.children`. The
// renderer reads from there directly.
const processBlocks = (blocks) => {
  if (!blocks || !Array.isArray(blocks)) return [];

  const result = [];
  let currentListType = null;
  let currentListItems = [];

  const flushList = (index) => {
    if (currentListType && currentListItems.length > 0) {
      result.push({
        id: `${currentListType}-${index}`,
        type: currentListType,
        children: [...currentListItems],
      });
    }
    currentListType = null;
    currentListItems = [];
  };

  blocks.forEach((block, index) => {
    if (block.type === 'bulleted_list_item') {
      if (currentListType !== 'bulleted_list') flushList(index);
      currentListType = 'bulleted_list';
      currentListItems.push(block);
    } else if (block.type === 'numbered_list_item') {
      if (currentListType !== 'numbered_list') flushList(index);
      currentListType = 'numbered_list';
      currentListItems.push(block);
    } else {
      flushList(index);
      result.push(block);
    }
  });

  flushList(blocks.length);
  return result;
};

export default async function Article({ jcontext, ...attributes }) {
  // Auto-detect database from fetch_data if not provided
  const { fetch_data = {} } = jcontext;
  const fetchDataKeys = Object.keys(fetch_data);

  // Smart database detection:
  // 1. Use explicit database attribute if provided
  // 2. If only one fetch_data key exists, use it automatically
  // 3. If multiple keys, use the first one (or could error)
  let autoDetectedDatabase = attributes.database;

  if (!autoDetectedDatabase && fetchDataKeys.length > 0) {
    autoDetectedDatabase = fetchDataKeys[0];
    // Optional: Log a warning if multiple keys exist
    if (fetchDataKeys.length > 1) {
      console.warn(
        `Article component: Multiple fetch_data keys found [${fetchDataKeys.join(', ')}]. ` +
        `Auto-using "${autoDetectedDatabase}". Specify explicitly via database attribute if needed.`
      );
    }
  }

  // New nested API with defaults - attributes come directly from JSON page
  const {
    database = autoDetectedDatabase || 'data',
    navigation = {},
    display = {},
    share = {},
    fields = {},
    styles = {}
  } = attributes;

  // Detect theme from jcontext - default to light if not specified
  const isDarkTheme = jcontext?.theme?.defaultColorScheme === 'dark';

  // Navigation options
  const {
    backLink = '/',
    backLabel = '← Back to all posts'
  } = navigation;

  // Display options
  const {
    showDescription = false,
    showCoverImage = true,
    showIcon = true,
    showAudio = true,
    defaultImage = null
  } = display;

  // Share options
  const {
    enabled: shareEnabled = true,
    networks: shareNetworks = ['linkedin', 'whatsapp', 'twitter', 'facebook']
  } = share;

  // Field mapping - Notion default field names
  const {
    title: titleField = 'Title',
    description: descriptionField = 'Description',
    author: authorField = 'Author',
    tags: tagsField = 'Tags',
    date: dateField = 'Date',
    language: languageField = 'Language',
    image: imageField = 'Image'
  } = fields;

  // Theme-adaptive prose classes (applied automatically, can't be overridden incorrectly)
  const themeProseClasses = isDarkTheme
    ? 'prose-invert prose-headings:text-white prose-a:text-blue-400 prose-strong:text-white prose-p:text-gray-300'
    : 'prose-headings:text-gray-900 prose-a:text-blue-600 prose-strong:text-gray-900 prose-p:text-gray-700';

  // Theme-adaptive default styles
  const defaultStyles = isDarkTheme ? {
    container: 'bg-transparent min-h-screen',
    article: 'max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-8',
    title: 'text-4xl md:text-4xl font-bold mb-5 text-white',
    descriptionStyle: 'text-lg text-gray-400 mt-2',
    coverImage: 'object-cover w-full',
    contentBase: 'mt-8 prose prose-lg max-w-none prose-p:leading-relaxed prose-p:text-pretty prose-headings:text-balance',
    backLinkStyle: 'text-gray-400 hover:text-blue-400 underline inline-block mb-4',
    textColor: 'text-gray-300',
    audioContainer: 'p-4 bg-gray-800/50 rounded-lg mb-8'
  } : {
    // Light theme defaults
    container: 'bg-transparent min-h-screen',
    article: 'max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-8',
    title: 'text-4xl md:text-4xl font-bold mb-5 text-gray-900',
    descriptionStyle: 'text-lg text-gray-600 mt-2',
    coverImage: 'object-cover w-full',
    contentBase: 'mt-8 prose prose-lg max-w-none prose-p:leading-relaxed prose-p:text-pretty prose-headings:text-balance',
    backLinkStyle: 'text-gray-600 hover:text-blue-600 underline inline-block mb-4',
    textColor: 'text-gray-700',
    audioContainer: 'p-4 bg-gray-100 rounded-lg mb-8'
  };

  // Merge user styles with theme-adaptive defaults (user styles take precedence)
  const {
    container = defaultStyles.container,
    article = defaultStyles.article,
    title = defaultStyles.title,
    description: descriptionStyle = defaultStyles.descriptionStyle,
    coverImage = defaultStyles.coverImage,
    content: contentBase = defaultStyles.contentBase,
    backLinkStyle = defaultStyles.backLinkStyle,
    textColor = defaultStyles.textColor,
    audioContainer = defaultStyles.audioContainer
  } = styles;

  // Strip any prose-invert from user-provided content styles (theme handles this automatically)
  // Then combine with theme-appropriate prose classes
  const cleanContentBase = contentBase.replace(/prose-invert/g, '').trim();
  const content = `${cleanContentBase} ${themeProseClasses}`;

  const page = fetch_data[database] || {};
  const blocks = page?.blocks || [];

  if (!page || (typeof page === 'object' && Object.keys(page).length === 0)) {
    return <div className={`text-center p-4 ${textColor}`}>Article not found or data is incomplete</div>;
  }

  const processedBlocks = processBlocks(blocks);

  // Get current URL from jcontext
  const currentUrl = jcontext?.url ||
    (jcontext?.domain && jcontext?.path
      ? `https://${jcontext.domain}${jcontext.path}`
      : '');

  // Extract page data using field mapping with fallbacks
  const pageTitle = page[titleField] || page.Title || 'Untitled';
  const pageDescription = page[descriptionField] || page.Description || '';
  const pageAuthor = page[authorField] || page.Author || '';
  const pageTags = page[tagsField] || page.Tags || [];
  const pageDate = page[dateField] || page.Date || page.updatedAt || page.createdAt;
  const pageLanguage = page[languageField] || page.Language || jcontext?.language || 'en';
  // Image priority: configured field > Notion's `cover` > generic `Image` > component default
  const articleImage = page[imageField] || page.cover || page.Image || null;
  const pageCoverImage = articleImage || defaultImage;
  const usingDefaultImage = !articleImage && !!defaultImage;
  const icon = page.icon;

  // Calculate word count for GEO
  const calculateWordCount = (blocks) => {
    if (!Array.isArray(blocks)) return 0;
    let wordCount = 0;
    blocks.forEach(block => {
      if (block.paragraph?.rich_text) {
        block.paragraph.rich_text.forEach(text => {
          wordCount += (text.plain_text || '').split(/\s+/).filter(Boolean).length;
        });
      }
      if (block.children) wordCount += calculateWordCount(block.children);
    });
    return wordCount;
  };

  const wordCount = calculateWordCount(blocks);
  const readTime = Math.max(1, Math.ceil(wordCount / 200)); // Average reading speed: 200 words/min

  // Prepare structured data. Only declare image dimensions when we know them
  // (article cover assumed 1200×630 OG-friendly; defaults could be any ratio).
  const structuredImage = pageCoverImage ? {
    "@type": "ImageObject",
    "url": pageCoverImage,
    ...(usingDefaultImage ? {} : { "width": 1200, "height": 630 })
  } : undefined;

  const structuredData = {
    "@context": "https://schema.org",
    "@type": "Article",
    "headline": pageTitle,
    "description": pageDescription,
    "image": structuredImage,
    "datePublished": pageDate ? new Date(pageDate).toISOString() : undefined,
    "dateModified": page.updatedAt ? new Date(page.updatedAt).toISOString() : (pageDate ? new Date(pageDate).toISOString() : undefined),
    "author": pageAuthor ? {
      "@type": "Person",
      "name": pageAuthor
    } : undefined,
    "publisher": {
      "@type": "Organization",
      "name": jcontext?.site?.name || "Blog",
      "logo": jcontext?.site?.logo ? {
        "@type": "ImageObject",
        "url": jcontext.site.logo
      } : undefined
    },
    "wordCount": wordCount > 0 ? wordCount : undefined,
    "timeRequired": wordCount > 0 ? `PT${readTime}M` : undefined,
    "inLanguage": pageLanguage,
    "keywords": Array.isArray(pageTags) && pageTags.length > 0
      ? pageTags.join(', ')
      : (typeof pageTags === 'string' && pageTags ? pageTags : undefined),
    "url": currentUrl || undefined,
    "mainEntityOfPage": currentUrl ? {
      "@type": "WebPage",
      "@id": currentUrl
    } : undefined
  };

  // Remove undefined properties
  Object.keys(structuredData).forEach(key =>
    structuredData[key] === undefined && delete structuredData[key]
  );
  if (structuredData.publisher.logo === undefined) delete structuredData.publisher.logo;

  // Find audio file
  let audioFile = page.Audio || page.audioFile || null;
  if (!audioFile && page.Files && Array.isArray(page.Files)) {
    audioFile = page.Files.find(file => {
      if (typeof file === 'string') {
        const lowerFile = file.toLowerCase();
        return lowerFile.endsWith('.mp3') || lowerFile.endsWith('.wav') ||
               lowerFile.endsWith('.ogg') || lowerFile.endsWith('.m4a');
      }
      return false;
    });
  }

  return (
    <div className={`${container} ${textColor}`} lang={pageLanguage}>
      {showCoverImage && pageCoverImage && (
        <div className="relative h-48 md:h-64 w-full mb-8">
          <ServerImage
            src={pageCoverImage}
            alt={usingDefaultImage
              ? pageTitle
              : `${pageTitle}${pageAuthor ? ` - by ${pageAuthor}` : ''}${pageDescription ? `. ${pageDescription.substring(0, 100)}` : ''}`}
            className={coverImage}
            priority={true}
            sizes="100vw"
            width={1200}
            height={630}
          />
        </div>
      )}

      <article className={`${article} ${textColor}`}>
        {/* JSON-LD Structured Data for SEO & AI Engines (GEO) */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(structuredData)
          }}
        />

        <div className="mb-8 flex justify-between items-center">
          <Link href={backLink} className={backLinkStyle}>{backLabel}</Link>
          {shareEnabled && (
            <ShareButton
              url={currentUrl}
              title={pageTitle}
              description={pageDescription}
              language={pageLanguage}
              options={{ socialNetworks: shareNetworks }}
              variant="elegant"
            />
          )}
        </div>

        <div className="mb-8">
          {showIcon && icon && (
            <div className="text-4xl mb-3">
              {typeof icon === 'string' && icon.length <= 2 ? icon : (
                <div className="relative w-12 h-12">
                  <ServerImage src={icon} alt="" className="rounded-lg" sizes="48px" />
                </div>
              )}
            </div>
          )}
          <h1 className={title}>{pageTitle}</h1>
          {showDescription && pageDescription && (
            <p className={descriptionStyle}>{pageDescription}</p>
          )}
        </div>

        {showAudio && audioFile && (
          <div className={audioContainer}>
            <div className="flex items-center gap-3 mb-2">
              <svg xmlns="http://www.w3.org/2000/svg" className={`h-5 w-5 ${isDarkTheme ? 'text-blue-400' : 'text-blue-600'}`} viewBox="0 0 20 20" fill="currentColor">
                <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM9.555 7.168A1 1 0 008 8v4a1 1 0 001.555.832l3-2a1 1 0 000-1.664l-3-2z" clipRule="evenodd" />
              </svg>
              <span className={`${isDarkTheme ? 'text-gray-300' : 'text-gray-700'} font-medium`}>Listen to this article</span>
            </div>
            <ServerAudio src={audioFile} preload="metadata" className="audio-player" />
          </div>
        )}

        <div className={`${content}`}>
          {Array.isArray(processedBlocks) ? (
            processedBlocks.map((block, index) => (
              <React.Fragment key={block.id || `block-${index}`}>
                {renderBlock(block, null, null, isDarkTheme)}
              </React.Fragment>
            ))
          ) : (
            <div>No content available</div>
          )}
        </div>

        <div className="mt-8 flex justify-between items-center">
          <Link href={backLink} className={backLinkStyle}>{backLabel}</Link>
          {shareEnabled && (
            <ShareButton
              url={currentUrl}
              title={pageTitle}
              description={pageDescription}
              language={pageLanguage}
              options={{ socialNetworks: shareNetworks }}
              variant="elegant"
            />
          )}
        </div>
      </article>
    </div>
  );
}
